<a href="https://colab.research.google.com/github/e-junior/Grupo16TechChallenge/blob/main/data_consumo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df_oiv = pd.read_excel('data oiv.xlsx')

In [ ]:
df_oiv = df_oiv.drop('Continent', axis=1)

In [7]:
df_oiv.dtypes

Continent          object
Region/Country     object
Product            object
Variable           object
Year              float64
Unit               object
Quantity          float64
dtype: object

In [9]:
df_oiv['Year'] = df_oiv['Year'].astype(str)

In [18]:
df_oiv.columns

Index(['Region/Country', 'Product', 'Variable', 'Year', 'Unit', 'Quantity'], dtype='object')

In [19]:
df_oiv.columns = ['pais', 'produto', 'variavel', 'ano', 'unidade', 'volume']

In [22]:
df_oiv.head()

          pais       produto     variavel     ano unidade    volume
0  Afghanistan  Dried Grapes  Consumption  2008.0  tonnes    6672.0
1  Afghanistan  Table Grapes  Consumption  2008.0  tonnes  187063.0
2  Afghanistan  Dried Grapes  Consumption  2009.0  tonnes     986.0
3  Afghanistan  Table Grapes  Consumption  2009.0  tonnes  257849.0
4  Afghanistan  Dried Grapes  Consumption  2010.0  tonnes    9729.0