## Importação de bibliotecas

In [21]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd

## Visualização inicial dos dados

In [112]:
df = pd.read_csv('Obesity.csv')

In [53]:
df.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

## Tratamento dos dados

In [24]:
df.isnull().sum().sum()     # Verifying null values in the dataset

0

In [25]:
df.isna().sum().sum()       # verifying NaN values in the dataset

0

In [113]:
df.columns = ['sexo',
              'idade',                              # renaming columns to acess porposes 
              'altura',
              'peso',
              'historico_familiar',
              'f_caloricos',
              'f_vegetais',
              'numero_refeicoes',
              'alimentacao_entre_refeicoes',
              'tabagista',
              'consumo_agua',
              'monitora_calorias',
              'frequencia_exercicio',
              'tempo_tela',
              'consumo_alcool',
              'meio_locomocao',
              'obesidade']

In [ ]:
df.info()

In [ ]:
#função para onde encontrar yes ou no substituir por True ou False  
def yes_no_to_bool(column):
    df[column] = df[column].map({'yes': True, 'no': False})

yes_no_to_bool('historico_familiar')
yes_no_to_bool('f_caloricos')
yes_no_to_bool('tabagista')

In [ ]:
# definindo função para categorizar valores de colunas de tempo em '0', '1', '2', '3' (nenhum, baixo, médio, alto)      

def categorize_time(value):
    if value == 0:
        return '0'
    elif value <  2:
        return '1'
    elif 2 <= value <= 5:
        return '2'
    else:
        return '3'

df['tempo_tela'] = df['tempo_tela'].apply(categorize_time)

In [ ]:
# definindo função para categorizar valores de colunas de tempo em '0', '1', '2', '3' (nenhum, baixo, médio, alto)      

def categorize_time(value):
    if value == 0:
        return '0'
    elif value <=  2:
        return '1'
    elif 2 < value <=4:
        return '2'
    else:
        return '3'

df['frequencia_exercicio'] = df['frequencia_exercicio'].apply(categorize_time)

In [ ]:
# definindo função para categorizar valores de colunas de tempo em '0', '1', '2', '3' (nenhum, baixo, médio, alto)      

def categorize_time(value):
    if value == 0:
        return '0'
    elif value <=  1:
        return '1'
    elif 1 < value <=2:
        return '2'
    else:
        return '3'

df['consumo_agua'] = df['consumo_agua'].apply(categorize_time)

In [130]:
# definindo função para categorizar valores de colunas de frequencia em '0', '1', '2', '3' (nenhum, baixo, médio, alto)
def categorize_frequency(column):
    df[column] = df[column].apply(
        lambda x: '0' if x == 0 else ('1' if 0 < x <= 2 else ('2' if 2 < x <= 3 else '3'))
    )
categorize_frequency('f_vegetais')

In [ ]:
# função para eliminar dados com ruidos decimais.

def remove_decimal_noise(column):
    df[column] = df[column].apply(lambda x: round(x, 0) )
    
remove_decimal_noise('idade')
remove_decimal_noise('f_vegetais')
remove_decimal_noise('numero_refeicoes')

In [ ]:
# função para padronizar altura e peso para dois digitos decimais

def standardize_two_decimal(column):
    df[column] = df[column].apply(lambda x: round(x, 2) )
    
standardize_two_decimal('peso')
standardize_two_decimal('altura')

In [126]:
# convertendo medidas de altura para centimetros
df['altura'] = df['altura'] * 100

In [134]:
df

,sexo,idade,altura,peso,historico_familiar,f_caloricos,f_vegetais,numero_refeicoes,alimentacao_entre_refeicoes,tabagista,consumo_agua,monitora_calorias,frequencia_exercicio,tempo_tela,consumo_alcool,meio_locomocao,obesidade
0,Female,21.0,162.0,64.00,True,False,1,3.0,Sometimes,False,2,no,0,1,no,Public_Transportation,Normal_Weight
1,Female,21.0,152.0,56.00,True,False,2,3.0,Sometimes,True,3,yes,2,0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,180.0,77.00,True,False,1,3.0,Sometimes,False,2,no,1,1,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,180.0,87.00,False,False,2,3.0,Sometimes,False,2,no,1,0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,178.0,89.80,False,False,1,1.0,Sometimes,False,2,no,0,0,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,21.0,171.0,131.41,True,True,2,3.0,Sometimes,False,2,no,1,1,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,22.0,175.0,133.74,True,True,2,3.0,Sometimes,False,3,no,1,1,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,23.0,175.0,133.69,True,True,2,3.0,Sometimes,False,3,no,1,1,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.0,174.0,133.35,True,True,2,3.0,Sometimes,False,3,no,1,1,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24.0,174.0,133.47,True,True,2,3.0,Sometimes,False,3,no,1,1,Sometimes,Public_Transportation,Obesity_Type_III